name: cypress run api tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3
        
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
      # Cache Cypress binary
      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      # Install dependencies and Cypress binary
      - name: Install dependencies and Cypress binary
        run: |
          npm install
          npx cypress install

      # Run the tests
      - name: Run Cypress API Tests
        env:
          CYPRESS_BASE_URL: 'http://localhost:8080/api' # Update with your API base URL
        run: npx cypress run
